FROM almalinux:9
ENV COURSE="Devops" \
    TRAINER="kotadurga" \
    DURATION="120hrs"
ARG LANGUAGE="Telugu"
RUN echo "I am Learning course is:${COURSE}, trainer is:${TRAINER},duration is:${DURATION},Language is:${LANGUAGE}"
CMD ["sleep","1000"]
